language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27-test
        - python: 3.3
          env: TOXENV=py33-test
        - python: 3.4
          env: TOXENV=py34-test
        - python: 3.5
          env: TOXENV=py35-test
        - python: 3.6
          env: TOXENV=py36-test
install:
    - pip install tox
    - pip install python-coveralls
script:
    - tox
    - coveralls --data_file .coverage.${TOXENV}
